on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: make build
      - name: version
        run: echo "::set-output name=version::$(./bin/linux-amd64/hs -version)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: checkout repo
        uses: actions/checkout@v4
      - name: build release
        run: make release
      - name: upload linux amd64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hs.linux-amd64.tar.gz
          asset_name: hs.linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin arm64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hs.darwin-arm64.tar.gz
          asset_name: hs.darwin-arm64.tar.gz
          asset_content_type: application/gzip
      - name: upload darwin amd64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hs.darwin-amd64.tar.gz
          asset_name: hs.darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - name: upload windows amd64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/hs.windows-amd64.zip
          asset_name: hs.windows-amd64.zip
          asset_content_type: application/zip